// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/error": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/accounts": {
    params: {};
  };
  "/accounts/create": {
    params: {};
  };
  "/accounts/:id": {
    params: {
      "id": string;
    };
  };
  "/accounts/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/items": {
    params: {};
  };
  "/items/create": {
    params: {};
  };
  "/items/:id": {
    params: {
      "id": string;
    };
  };
  "/items/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/boxes": {
    params: {};
  };
  "/boxes/create": {
    params: {};
  };
  "/boxes/:id": {
    params: {
      "id": string;
    };
  };
  "/boxes/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/inventory": {
    params: {};
  };
  "/inventory/create": {
    params: {};
  };
  "/inventory/:id": {
    params: {
      "id": string;
    };
  };
  "/inventory/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/orders": {
    params: {};
  };
  "/orders/create": {
    params: {};
  };
  "/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/orders/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/shipments": {
    params: {};
  };
  "/shipments/create": {
    params: {};
  };
  "/shipments/:id": {
    params: {
      "id": string;
    };
  };
  "/shipments/:id/edit": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/error" | "/about" | "/accounts" | "/accounts/create" | "/accounts/:id" | "/accounts/:id/edit" | "/items" | "/items/create" | "/items/:id" | "/items/:id/edit" | "/boxes" | "/boxes/create" | "/boxes/:id" | "/boxes/:id/edit" | "/inventory" | "/inventory/create" | "/inventory/:id" | "/inventory/:id/edit" | "/orders" | "/orders/create" | "/orders/:id" | "/orders/:id/edit" | "/shipments" | "/shipments/create" | "/shipments/:id" | "/shipments/:id/edit";
  };
  "../components/Home.tsx": {
    id: "../components/Home";
    page: "/";
  };
  "../components/utility/LoginForm.tsx": {
    id: "../components/utility/LoginForm";
    page: "/login";
  };
  "../components/utility/Logout.tsx": {
    id: "../components/utility/Logout";
    page: "/logout";
  };
  "../features/errors/Error.tsx": {
    id: "../features/errors/Error";
    page: "/error";
  };
  "../components/utility/About.tsx": {
    id: "../components/utility/About";
    page: "/about";
  };
  "../features/accounts/Accounts.tsx": {
    id: "../features/accounts/Accounts";
    page: "/accounts";
  };
  "../features/accounts/CreateAccount.tsx": {
    id: "../features/accounts/CreateAccount";
    page: "/accounts/create";
  };
  "../features/accounts/ViewAccount.tsx": {
    id: "../features/accounts/ViewAccount";
    page: "/accounts/:id";
  };
  "../features/accounts/EditAccount.tsx": {
    id: "../features/accounts/EditAccount";
    page: "/accounts/:id/edit";
  };
  "../features/items/Items.tsx": {
    id: "../features/items/Items";
    page: "/items";
  };
  "../features/items/CreateItem.tsx": {
    id: "../features/items/CreateItem";
    page: "/items/create";
  };
  "../features/items/ViewItem.tsx": {
    id: "../features/items/ViewItem";
    page: "/items/:id";
  };
  "../features/items/EditItem.tsx": {
    id: "../features/items/EditItem";
    page: "/items/:id/edit";
  };
  "../features/boxes/Boxes.tsx": {
    id: "../features/boxes/Boxes";
    page: "/boxes";
  };
  "../features/boxes/CreateBox.tsx": {
    id: "../features/boxes/CreateBox";
    page: "/boxes/create";
  };
  "../features/boxes/ViewBox.tsx": {
    id: "../features/boxes/ViewBox";
    page: "/boxes/:id";
  };
  "../features/boxes/EditBox.tsx": {
    id: "../features/boxes/EditBox";
    page: "/boxes/:id/edit";
  };
  "../features/inventory/Inventory.tsx": {
    id: "../features/inventory/Inventory";
    page: "/inventory";
  };
  "../features/inventory/CreateInventory.tsx": {
    id: "../features/inventory/CreateInventory";
    page: "/inventory/create";
  };
  "../features/inventory/ViewInventory.tsx": {
    id: "../features/inventory/ViewInventory";
    page: "/inventory/:id";
  };
  "../features/inventory/EditInventory.tsx": {
    id: "../features/inventory/EditInventory";
    page: "/inventory/:id/edit";
  };
  "../features/orders/Orders.tsx": {
    id: "../features/orders/Orders";
    page: "/orders";
  };
  "../features/orders/CreateOrder.tsx": {
    id: "../features/orders/CreateOrder";
    page: "/orders/create";
  };
  "../features/orders/ViewOrder.tsx": {
    id: "../features/orders/ViewOrder";
    page: "/orders/:id";
  };
  "../features/orders/EditOrder.tsx": {
    id: "../features/orders/EditOrder";
    page: "/orders/:id/edit";
  };
  "../features/shipments/Shipments.tsx": {
    id: "../features/shipments/Shipments";
    page: "/shipments";
  };
  "../features/shipments/CreateShipment.tsx": {
    id: "../features/shipments/CreateShipment";
    page: "/shipments/create";
  };
  "../features/shipments/ViewShipment.tsx": {
    id: "../features/shipments/ViewShipment";
    page: "/shipments/:id";
  };
  "../features/shipments/EditShipment.tsx": {
    id: "../features/shipments/EditShipment";
    page: "/shipments/:id/edit";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "../components/Home": unknown;
  "../components/utility/LoginForm": unknown;
  "../components/utility/Logout": unknown;
  "../features/errors/Error": unknown;
  "../components/utility/About": unknown;
  "../features/accounts/Accounts": unknown;
  "../features/accounts/CreateAccount": unknown;
  "../features/accounts/ViewAccount": unknown;
  "../features/accounts/EditAccount": unknown;
  "../features/items/Items": unknown;
  "../features/items/CreateItem": unknown;
  "../features/items/ViewItem": unknown;
  "../features/items/EditItem": unknown;
  "../features/boxes/Boxes": unknown;
  "../features/boxes/CreateBox": unknown;
  "../features/boxes/ViewBox": unknown;
  "../features/boxes/EditBox": unknown;
  "../features/inventory/Inventory": unknown;
  "../features/inventory/CreateInventory": unknown;
  "../features/inventory/ViewInventory": unknown;
  "../features/inventory/EditInventory": unknown;
  "../features/orders/Orders": unknown;
  "../features/orders/CreateOrder": unknown;
  "../features/orders/ViewOrder": unknown;
  "../features/orders/EditOrder": unknown;
  "../features/shipments/Shipments": unknown;
  "../features/shipments/CreateShipment": unknown;
  "../features/shipments/ViewShipment": unknown;
  "../features/shipments/EditShipment": unknown;
};